Repository Lobotomy-Corporation-13/lc13, pull requests merged in 2025-08, with the labels that each got.

#31 Character Slot increase
  code/modules/client/preferences.dm
Labels: 2 Code Improvement / Refactor

#37 replaced da capo weapon sprite
  icons/obj/ego_weapons.dmi
Labels: 3 Sprites

#22 Hurting Teddy is no longer the best healing source in the game
  code/modules/mob/living/simple_animal/abnormality/teth/hurting_teddy.dm
Labels: 2 Fix

#32 More Roundend Info [DONE]
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/suppressions/_core_suppression.dm
  lobotomy-corp13.dme
Labels: 3 Expansion

#24 Shiptest Character Flavor Text Port [DONE]
  code/__DEFINES/misc.dm
  code/__DEFINES/say.dm
  code/__HELPERS/mobs.dm
  code/_onclick/hud/human.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/mob.dm
  code/modules/mob/say_vr.dm
  lobotomy-corp13.dme
Labels: 1 Feature

#27 Nuking Chaos Donuts
  code/modules/food_and_drinks/recipes/tablecraft/recipes_unusual.dm
Labels: 2 Code Improvement / Refactor

#34 Abno Update: Skin Prophet
  code/modules/mob/living/simple_animal/abnormality/teth/skin_prophet.dm
  code/modules/paperwork/records/info/teth.dm
Labels: 3 Expansion

#42 Flavor Text Unique Character Slot Hotfix
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: 2 Fix

#47 added a contained idle animation for QoH
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
Labels: 3 Sprites

#48 Dipsia Armour Resprite
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
Labels: 3 Sprites

#54 fixed skub's records
  ModularTegustation/!extra_abnos/joke_abnormalities/records.dm
Labels: 2 Fix

#2 Expedition machinery update 1.0 [DONE]
  ModularTegustation/Teguicons/expedition_32x32.dmi
  ModularTegustation/expedition/items.dm
  ModularTegustation/expedition/machinery.dm
  ModularTegustation/tegu_items/rcorp_factory/construction.dm
  ModularTegustation/tegu_items/rcorp_factory/machinery.dm
  lobotomy-corp13.dme
Labels: 3 Expansion

#26 Contempt, Awe E.G.O. Weapon Rework
  ModularTegustation/ego_weapons/melee/waw.dm
  icons/hud/screen_alert.dmi
Labels: 3 Expansion

#40 Updates the round end to give a completion Rank
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/ticker.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/suppressions/extraction.dm
Labels: 1 Feature

#57 CRA Breacher now sends the abnormality to a random xenospawn.
  ModularTegustation/tegu_items/disciplinary/research.dm
Labels: 2 Balance

#61 Hotfixes the CRA researcher
  ModularTegustation/tegu_items/disciplinary/research.dm
Labels: 2 Fix

#50 Ports "The Moon Rabbit" from Branch 12
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/ego_weapons/melee/teth.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/lunar_rabbit.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  lobotomy-corp13.dme
Labels: 1 Abnormality

#52 Possibly Awful Stacking Weather Effects [MIGHT LAG]
  code/datums/weather/weather.dm
Labels: 1 Feature

#20 Thumb East - CoL Antag and Thumb Facility Input
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/Teguicons/thumb_east_held_left.dmi
  ModularTegustation/Teguicons/thumb_east_held_right.dmi
  ModularTegustation/Teguicons/thumb_east_obj.dmi
  ModularTegustation/Teguicons/thumb_east_worn.dmi
  ModularTegustation/ego_weapons/melee/non_abnormality/thumb.dm
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/official_office.dm
  ModularTegustation/tegu_items/associations/syndicateoffice.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_items/refinery/_spawners.dm
  ModularTegustation/tegu_items/refinery/boxes.dm
  ModularTegustation/tegu_items/refinery/crates/syndicate.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  _maps/templates/syndicate_office/thumb_east.dmm
  code/modules/clothing/suits/ego_gear/non_abnormality/thumb.dm
  code/modules/jobs/job_types/city/syndicate/thumb_east/east_capo.dm
  code/modules/jobs/job_types/city/syndicate/thumb_east/east_soldato.dm
  code/modules/jobs/job_types/trusted_players/association/col_association.dm
  code/modules/jobs/jobs.dm
  code/modules/surgery/tools.dm
  icons/obj/stack_objects.dmi
  lobotomy-corp13.dme
  sound/weapons/ego/thumb_east_podao_attack.ogg
  sound/weapons/ego/thumb_east_podao_boostedlunge.ogg
  sound/weapons/ego/thumb_east_podao_boostedsweep.ogg
  sound/weapons/ego/thumb_east_podao_clash.ogg
  sound/weapons/ego/thumb_east_podao_detonation.ogg
  sound/weapons/ego/thumb_east_podao_leap_impact.ogg
  sound/weapons/ego/thumb_east_podao_leap_prep.ogg
  sound/weapons/ego/thumb_east_podao_reload_end.ogg
  sound/weapons/ego/thumb_east_podao_reload_load.ogg
  sound/weapons/ego/thumb_east_podao_reload_start.ogg
  sound/weapons/ego/thumb_east_rifle_attack.ogg
  sound/weapons/ego/thumb_east_rifle_boostedfinisher.ogg
  sound/weapons/ego/thumb_east_rifle_boostedlunge.ogg
  sound/weapons/ego/thumb_east_rifle_boostedsweep.ogg
  sound/weapons/ego/thumb_east_rifle_detonation.ogg
  sound/weapons/ego/thumb_east_rifle_reload_end.ogg
  sound/weapons/ego/thumb_east_rifle_reload_fail.ogg
  sound/weapons/ego/thumb_east_rifle_reload_load.ogg
  sound/weapons/ego/thumb_east_rifle_reload_start.ogg
Labels: 1 Feature

#69 Stock Market Withdrawls Hotfix
  code/modules/stock_market/stonk_computer.dm
Labels: 2 Fix

#28 [RCE] - Adds another filter to help sort the output of a factory
  _maps/map_files/Event/rcorp_factory.dmm
  code/modules/recycling/conveyor_filter.dm
  code/modules/recycling/filter_settings.dm
  icons/obj/conveyor_filters.dmi
  lobotomy-corp13.dme
Labels: 3 Expansion

#77 Readds visual work result overlays to Shock Centipede
  code/modules/mob/living/simple_animal/abnormality/he/shock_centipede.dm
Labels: 2 Fix

#76 Indigo Dusk Red Commander bugfix and minor healing nerf
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo/dusk.dm
Labels: 2 Fix

#59 Paper fix
  code/modules/paperwork/paper.dm
  code/modules/tgui/external.dm
  code/modules/tgui/tgui_chunking.dm
  lobotomy-corp13.dme
  tgui/packages/tgui/interfaces/PaperSheet.js
  tgui/public/tgui.html
Labels: 2 Fix

#73 Health Code Refactor
  code/__DEFINES/attributes.dm
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/maptype.dm
  code/datums/attributes/_attribute.dm
  code/datums/attributes/fortitude.dm
  code/datums/attributes/prudence.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: 2 Code Improvement / Refactor

#83 Violet Midnight Number Change
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: 2 Balance

#82 Armor Equipment Update
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
Labels: 2 Balance

#81 Bugfixes Lust Peccatula ranged immunity and bugfixes all known issues with Association skills
  ModularTegustation/tegu_items/associations/skills/liu/associate.dm
  ModularTegustation/tegu_items/associations/skills/liu/director.dm
  ModularTegustation/tegu_items/associations/skills/seven/associate.dm
  ModularTegustation/tegu_items/associations/skills/seven/director.dm
  ModularTegustation/tegu_items/associations/skills/seven/veteran.dm
  ModularTegustation/tegu_items/associations/skills/zwei/director.dm
  code/modules/mob/living/simple_animal/dc_changes.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
Labels: 2 Fix

#84 Flesh That Takes (Ollieoxenfree port)
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/ego_weapons/melee/waw.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_that_takes.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: 1 Abnormality

#55 Steel Midnight Act II
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel/corporals.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel/goons.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel/manager.dm
  code/modules/ordeals/steel_ordeals.dm
  lobotomy-corp13.dme
Labels: 1 Feature

#75 wacky deconstructable and damage visual for sandbags.
  ModularTegustation/Teguicons/sandbag_damage.dmi
  code/game/machinery/deployable.dm
Labels: 2 Code Improvement / Refactor

#11 Major City Update: Niaojia-ren
  ModularTegustation/Teguicons/room_spawners/17x12.dmi
  ModularTegustation/ego_weapons/_ego_weapon.dm
  ModularTegustation/tegu_mobs/lc13_cuckoospawn.dm
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/RandomRooms/backstreetlayout/lcorp_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/outskirts.dmm
  _maps/RandomRooms/backstreetlayout/ruinned_la_mancha_land.dmm
  _maps/RandomRooms/backstreetlayout/standard.dmm
  _maps/RandomRooms/backstreetlayout/tunnels_backstreets.dmm
  _maps/RandomRooms/backstreets/cuckoo_nest.dmm
  _maps/map_files/Event/city.dmm
  code/__DEFINES/melee.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/martial/cuckoopunch.dm
  code/datums/martial/wrestling.dm
  code/game/area/areas/lobotomy_corp.dm
  code/game/objects/effects/spawners/cuckoo_spawner.dm
  code/game/objects/structures/cuckoo_role_spawner.dm
  code/modules/admin/smites/claw_execute.dm
  code/modules/jobs/job_types/city/carnival.dm
  code/modules/jobs/job_types/trusted_players/association/roaming.dm
  code/modules/language/cuckospawn.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/cuckoospawn/cuckoospawn_embryo.dm
  code/modules/mob/living/carbon/human/species_types/cuckoospawn.dm
  code/modules/mob/living/simple_animal/friendly/eric_t.dm
  icons/mob/cuckoospawn.dmi
  icons/mob/cuckoospawn_big.dmi
  icons/mob/human_parts.dmi
  icons/mob/inhands/equipment/banners_lefthand.dmi
  icons/mob/inhands/equipment/banners_righthand.dmi
  icons/obj/banner.dmi
  lobotomy-corp13.dme
Labels: 3 Expansion

#4 City Gear Update: Dieci/Cinq Update (Also fanghunt, I guess)
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/ego_weapons/melee/non_abnormality/cinq.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/cinqwest_selfiestick.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/cinqwest_selfiestick_complete_implementation.md
  ModularTegustation/ego_weapons/melee/non_abnormality/dieci.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/cinq.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/dieci.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/fanghunt.dm
  code/modules/jobs/job_types/trusted_players/association/roaming.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: 1 Feature

#23 Time Ripper, a boulder atop the mountain, finally.
  ModularTegustation/Teguicons/ripper32x64.dmi
  ModularTegustation/Teguicons/ripper64x64.dmi
  code/modules/mob/living/simple_animal/distortion/nightmare/timeripper.dm
Labels: 1 Feature

#92 Time Ripper Hotfix
  lobotomy-corp13.dme
Labels: 2 Fix

#94 Facility Rank will no longer show up if you don't have one
  code/__HELPERS/roundend.dm
Labels: 2 Fix

#93 Fixes the Shi South 2 Sprite
  icons/mob/clothing/ego_gear/lc13_armor.dmi
Labels: 2 Fix

#104 Nerfs Ardor Blossom Star
  ModularLobotomy/ego_weapons/ranged/ego_bullets/he.dm
  ModularLobotomy/ego_weapons/ranged/he.dm
Labels: 2 Balance

#109 Addas an ability for the Patch E.G.O weapon.
  ModularLobotomy/ego_weapons/melee/abnormality/teth.dm
Labels: 3 Expansion

#115 Autoloader Cooldown Fix
  ModularLobotomy/moba_skills/ranged/autoloader.dm
Labels: 2 Fix

#114 Changes to Jekyll's Records (No more surprise insanity)
  code/modules/paperwork/records/info/tools.dm
Labels: 2 Fix

#111 Prevents Big Bird from having extra range from him attacking while moving
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
Labels: 2 Fix

#112 Adds Proc call mode to build mode
  code/__HELPERS/datums.dm
  code/modules/buildmode/submodes/proccall.dm
  icons/misc/buildmode.dmi
  lobotomy-corp13.dme
Labels: 3 Expansion

#120 Replaces one of the two Clerks with Assistinator
  code/modules/jobs/job_types/assistant.dm
Labels: 2 Fix

#125 fixes attribute requirements for flesh that takes weapon and records
  ModularLobotomy/ego_weapons/melee/abnormality/waw.dm
  code/modules/paperwork/records/info/waw.dm
Labels: 2 Fix

#25 A wild Star Luminary has appeared!!
  ModularLobotomy/_Lobotomyicons/32x32.dmi
  ModularLobotomy/_Lobotomyicons/status_sprites.dmi
  ModularLobotomy/ego_weapons/melee/abnormality/aleph.dm
  code/datums/abnormality/_ego_datum/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/star_luminary.dm
  code/modules/paperwork/records/info/aleph.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: 1 Abnormality

#128 Adds Gamespeed and Station Trait to the Stat Panel
  code/controllers/subsystem/statpanel.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: 3 Expansion

#126 Adds more emojis to OOC and DChat
  icons/emoji.dmi
Labels: 3 Sprites
