Repository Lobotomy-Corporation-13/lc13, pull requests merged in 2025-09, with the labels that each got.

#131 Fixes Void Dream not firing sleepy darts, and readds it to RCA
  ModularLobotomy/rcorp/landmarks.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
Labels: 2 Fix

#110 Banquet E.G.O. weapon rework and reflavour
  ModularLobotomy/ego_weapons/ranged/ego_bullets/waw.dm
  ModularLobotomy/ego_weapons/ranged/waw.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
  sound/weapons/ego/banquet_fire.ogg
Labels: 3 Expansion, 3 Sprites

#127 Add: Expand GitHub PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4 GitHub

#123 Port/Adapt: tgstation/mothblocks "Move auto changelog generation into… ee568cd … its own workflow (#70652)
  .github/workflows/auto_changelog.yml
  .github/workflows/compile_changelogs.yml
  tools/pull_request_hooks/autoChangelog.js
  tools/pull_request_hooks/autoChangelog.test.js
  tools/pull_request_hooks/changelogConfig.js
  tools/pull_request_hooks/changelogParser.js
  tools/pull_request_hooks/changelogParser.test.js
  tools/pull_request_hooks/package.json
Labels: 4 GitHub, 2 Javascript

#3 Minor City Update: Migo buff/Ruined Town nerf
  _maps/Quests/ruined_town.dmm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
Labels: 2 Balance

#143 Ports the balloon alerts from /T.G./ Station.
  code/__DEFINES/layers.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/text.dm
  code/__HELPERS/game.dm
  code/datums/chatmessage.dm
  code/modules/baloon_alert/baloon_alert.dm
  code/modules/reagents/reagent_containers.dm
  lobotomy-corp13.dme
Labels: 1 Feature

#145 Core Suppressions for Manager-less shifts
  ModularLobotomy/lc13_obj/lc13_computers/abnormality_auxiliary.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/ticker.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/ordeals/_ordeal.dm
Labels: 1 Feature

#150 Freischütz teleport visible message & louder SFX
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
Labels: 3 Expansion

#142 Fires are Extinguishable Now [Seems to Work]
  ModularLobotomy/associations/skills/liu/associate.dm
  ModularLobotomy/associations/skills/liu/director.dm
  ModularLobotomy/associations/skills/liu/veteran.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/effects/abnormality.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/abnormality/he/ardor_blossom_moth.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: 2 Balance, 2 Fix

#156 Add: Ping on Discord if player number meets or exceeds a new config value
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/discord.dm
  config/example/config.txt
Labels: 1 Feature, Test Merge Candidate

#152 Expedition machinery update 1.1 [DONE]
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/mob_helpers.dm
  code/modules/rce/machinery.dm
Labels: 2 Balance

#154 Balloon Text Abno Work
  ModularLobotomy/!extra_abnos/joke_abnormalities/aleph/wild_ride.dm
  ModularLobotomy/lc13_obj/lc13_computers/abnormality_work.dm
  code/__DEFINES/~lobotomy_defines/abnormalities.dm
  code/modules/baloon_alert/baloon_alert.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
  code/modules/mob/living/simple_animal/abnormality/teth/pale_horse.dm
  code/modules/mob/living/simple_animal/abnormality/teth/someonesportrait.dm
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/mob/living/simple_animal/abnormality/waw/siltcurrent.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  lobotomy-corp13.dme
Labels: 1 Feature

#134 Carnival took a trip to the prosthetic workshop for their stuff
  ModularLobotomy/associations/vending.dm
  ModularLobotomy/prosthetics/carnival.dm
  ModularLobotomy/prosthetics/chainsword.dm
  ModularLobotomy/prosthetics/fixertools.dm
  ModularLobotomy/prosthetics/mantis.dm
  ModularLobotomy/prosthetics/scrying.dm
  ModularLobotomy/prosthetics/storage.dm
  _maps/map_files/Event/city.dmm
  code/datums/outfit.dm
  code/game/objects/items/stacks/sheets/silk.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/_ego_masks.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/carnival.dm
  code/modules/jobs/job_types/city/carnival.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/spells/ability_types/_ability.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/surgery_helpers.dm
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/mask.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/human_parts.dmi
  icons/obj/clothing/ego_gear/masks.dmi
  lobotomy-corp13.dme
Labels: 3 Expansion, 3 Mapping

#161 Add: Expansion to the HighPopQueue, now accepts Discord queuers
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/discord.dm
  code/modules/discord/tgs_commands.dm
  config/example/config.txt
Labels: 3 Expansion, 6 Config
